spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true



